// AXIOM Nabla — Build Script
//
// Reads protocol_nabla.toml and generates src/tuning_gen.rs with compile-time
// constants. A `foo` + `foo_dev` PAIR emits ONE constant under the base name,
// selected by the `dev-tuning` feature (KI#240 — was `dev-mode`; same split as
// protocol_lambda.toml's KI#136 `dev-tuning`: VALUES ONLY, so a `--dev` launch no
// longer drags dev timing onto a ceremony-keyed network). A standalone key emits a single always-on constant.
// No external dependencies — uses only std.
use std::fs;
use std::path::Path;

fn main() {
    let conf_path = Path::new("protocol_nabla.toml");
    println!("cargo:rerun-if-changed=protocol_nabla.toml");

    let content = fs::read_to_string(conf_path)
        .unwrap_or_else(|e| panic!("Cannot read protocol_nabla.toml: {}", e));

    // Pass 1: collect KEY = VALUE (skip blanks / # comments / [sections]).
    let mut entries: Vec<(String, String)> = Vec::new();
    for (line_num, line) in content.lines().enumerate() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') || line.starts_with('[') {
            continue;
        }
        let parts: Vec<&str> = line.splitn(2, '=').collect();
        if parts.len() != 2 {
            panic!(
                "protocol_nabla.toml line {}: expected KEY = VALUE, got: {}",
                line_num + 1,
                line
            );
        }
        let key = parts[0].trim().to_string();
        // Strip inline comment + underscore separators: "17_280  # 24h" → "17280".
        let val_str = parts[1].split('#').next().unwrap().trim().replace('_', "");
        val_str.parse::<u64>().unwrap_or_else(|e| {
            panic!("protocol_nabla.toml line {}: cannot parse '{}' as u64: {}", line_num + 1, val_str, e)
        });
        entries.push((key, val_str));
    }

    // Pass 2: emit, honoring the `_dev`-pair convention.
    let has = |name: &str| entries.iter().any(|(k, _)| k == name);
    let mut out = String::from(
        "// AUTO-GENERATED by build.rs from protocol_nabla.toml\n// DO NOT EDIT — edit protocol_nabla.toml instead.\n\n",
    );
    for (key, value) in &entries {
        if let Some(base) = key.strip_suffix("_dev") {
            if has(base) {
                out.push_str(&format!(
                    "#[cfg(feature = \"dev-tuning\")]\npub const {}: u64 = {};\n",
                    base.to_uppercase(),
                    value
                ));
                continue;
            }
        }
        if has(&format!("{key}_dev")) {
            out.push_str(&format!(
                "#[cfg(not(feature = \"dev-tuning\"))]\npub const {}: u64 = {};\n",
                key.to_uppercase(),
                value
            ));
            continue;
        }
        out.push_str(&format!("pub const {}: u64 = {};\n", key.to_uppercase(), value));
    }

    fs::write(Path::new("src/tuning_gen.rs"), out)
        .unwrap_or_else(|e| panic!("Cannot write src/tuning_gen.rs: {}", e));
}
